# Generated by Django 2.2 on 2023-08-10 15:36

from typing import List
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=50)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'activity_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_of_campaign', models.DateField(blank=True)),
                ('description', models.TextField()),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=50)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'campaign_activity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'campaign_contact',
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('nlm', models.CharField(blank=True, max_length=50)),
                ('nn_embedding', models.CharField(blank=True, max_length=50)),
                ('prompt', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'chatbot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('country_id', models.IntegerField(null=True)),
                ('currently_visiting', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('first_name', models.CharField(max_length=50)),
                ('hashed_pwd', models.BinaryField(null=True)),
                ('salt', models.BinaryField(null=True)),
                ('surname', models.CharField(max_length=50)),
                ('linkedin_url', models.CharField(blank=True, max_length=200)),
                ('member_id', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('opt_notes', models.TextField(blank=True)),
                ('opt_out', models.BooleanField(default=False)),
                ('phone_number', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('subdivision_id', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'corpus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('closed', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('member_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('outcome', models.TextField()),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'opportunity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QAndA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('answer', models.TextField()),
                ('question', models.TextField()),
                ('conversation_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='contact.Conversation',
                )),
            ],
            options={
                'db_table': 'q_and_a',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('hyperlink', models.URLField()),
                ('q_and_a_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.QAndA')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='OpportunityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('cc', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('heading', models.CharField(blank=True, default='', max_length=50)),
                ('history_type', models.CharField(choices=[('email', 'email'), ('note', 'note')], max_length=5)),
                ('message', models.TextField()),
                ('reply_to', models.EmailField(max_length=250, null=True)),
                ('to', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user_id', models.IntegerField()),
                ('opportunity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='history',
                    to='contact.Opportunity',
                )),
            ],
            options={
                'db_table': 'opportunity_history',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('opportunity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='contact.Opportunity',
                )),
            ],
            options={
                'db_table': 'opportunity_contact',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contacts',
            field=models.ManyToManyField(
                related_name='opportunities',
                through='contact.OpportunityContact',
                to='contact.Contact',
            ),
        ),
        migrations.CreateModel(
            name='GroupContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Group')),
            ],
            options={
                'db_table': 'group_contact',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='contacts',
            field=models.ManyToManyField(related_name='groups', through='contact.GroupContact', to='contact.Contact'),
        ),
        migrations.CreateModel(
            name='CorpusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('hyperlink', models.URLField()),
                ('corpus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Corpus')),
            ],
            options={
                'db_table': 'corpus_data',
            },
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['created'], name='corpus_created'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['id'], name='corpus_id'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['member_id'], name='corpus_member_id'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['name'], name='corpus_name'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chatbot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Chatbot'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Contact'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['address'], name='contact_address'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['address2'], name='contact_address2'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['city'], name='contact_city'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company_name'], name='contact_company_name'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['country_id'], name='contact_country_id'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contact_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name'], name='contact_first_name'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['member_id'], name='contact_member_id'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['opt_out'], name='contact_opt_out'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone_number'], name='contact_phone_number'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['postcode'], name='contact_postcode'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['subdivision_id'], name='contact_subdivision_id'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['surname'], name='contact_surname'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['website'], name='contact_website'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['currently_visiting'], name='contact_visiting'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='corpus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Corpus'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Campaign'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Activity'),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(
                related_name='campaigns',
                through='contact.CampaignContact',
                to='contact.Contact',
            ),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['id'], name='activity_type_id'),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['member_id'], name='activity_type_member_id'),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['name'], name='activity_type_name'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='activities',
                to='contact.ActivityType',
            ),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['created'], name='reference_created'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['hyperlink'], name='reference_hyperlink'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['id'], name='reference_id'),
        ),
        migrations.AddIndex(
            model_name='qanda',
            index=models.Index(fields=['answer'], name='q_and_a_answer'),
        ),
        migrations.AddIndex(
            model_name='qanda',
            index=models.Index(fields=['created'], name='q_and_a_created'),
        ),
        migrations.AddIndex(
            model_name='qanda',
            index=models.Index(fields=['id'], name='q_and_a_id'),
        ),
        migrations.AddIndex(
            model_name='qanda',
            index=models.Index(fields=['question'], name='q_and_a_question'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitycontact',
            unique_together={('contact', 'opportunity')},
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['closed'], name='opportunity_closed'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['id'], name='opportunity_id'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['member_id'], name='opportunity_member_id'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['name'], name='opportunity_name'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['probability'], name='opportunity_probability'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['value'], name='opportunity_value'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcontact',
            unique_together={('group', 'contact')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['id'], name='group_id'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['member_id'], name='group_member_id'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='group_name'),
        ),
        migrations.AddIndex(
            model_name='corpusdata',
            index=models.Index(fields=['created'], name='corpus_data_created'),
        ),
        migrations.AddIndex(
            model_name='corpusdata',
            index=models.Index(fields=['hyperlink'], name='corpus_data_hyperlink'),
        ),
        migrations.AddIndex(
            model_name='corpusdata',
            index=models.Index(fields=['id'], name='corpus_data_id'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created'], name='conversation_created'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['id'], name='conversation_id'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['name'], name='conversation_name'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['created'], name='chatbot_created'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['id'], name='chatbot_id'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['member_id'], name='chatbot_member_id'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['name'], name='chatbot_name'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['nlm'], name='chatbot_nlm'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['nn_embedding'], name='chatbot_nn_embedding'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['prompt'], name='chatbot_prompt'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['responded'], name='campaign_contact_responded'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncontact',
            unique_together={('campaign', 'contact')},
        ),
        migrations.AddIndex(
            model_name='campaignactivity',
            index=models.Index(fields=['id'], name='campaign_activity_id'),
        ),
        migrations.AddIndex(
            model_name='campaignactivity',
            index=models.Index(fields=['name'], name='campaign_activity_name'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['date_of_campaign'], name='campaign_date_of_campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['id'], name='campaign_id'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['member_id'], name='campaign_member_id'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['name'], name='campaign_name'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['id'], name='acitivity_id'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['name'], name='activity_name'),
        ),
    ]
