# Generated by Django 2.2 on 2023-08-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_default_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='corpus_id',
            new_name='corpus',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='chatbot_id',
            new_name='chatbot',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='corpusdata',
            old_name='corpus_id',
            new_name='corpus',
        ),
        migrations.RenameField(
            model_name='qanda',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='q_and_a_id',
            new_name='q_and_a',
        ),
    ]
