# Generated by Django 2.2 on 2023-08-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_fix_chatbot_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='q_and_a',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='references',
                to='contact.QAndA',
            ),
        ),
    ]
