# Generated by Django 2.2 on 2023-08-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_references_as_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusdata',
            name='corpus',
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='corpus',
            name='corpus_member_id',
        ),
        migrations.RemoveIndex(
            model_name='corpus',
            name='corpus_name',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='name',
        ),
        migrations.AddField(
            model_name='corpus',
            name='chatbot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contact.Chatbot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='hyperlink',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['hyperlink'], name='corpus_hyperlink'),
        ),
        migrations.DeleteModel(
            name='CorpusData',
        ),
    ]
