# Generated by Django 2.2 on 2023-09-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_merge_chatbot_and_corpus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='acitivity_id',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['id'], name='activity_id'),
        ),
    ]
