# Generated by Django 2.2 on 2023-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_fix_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='agent_api_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='agent_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='agent_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
