# Generated by Django 2.2 on 2023-10-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_extend_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='agent_api_key',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='agent_email',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='agent_password',
        ),
    ]
