# Generated by Django 2.2 on 2023-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_remove_agent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='button_background_colour',
            field=models.CharField(default='#47B2E4', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='button_position_from_bottom',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='button_position_from_right',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='button_text',
            field=models.CharField(default='Chatbot', max_length=50),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='button_text_colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='welcome_text',
            field=models.CharField(default='Please login to Chatbot', max_length=255),
        ),
    ]
