# Generated by Django 2.2 on 2023-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_chatbot_properties'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_nlm',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='nlm',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(choices=[('chatgpt3', 'chatgpt3'), ('echo', 'echo')], default='echo', max_length=8),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['nn_llm'], name='chatbot_nn_llm'),
        ),
    ]
