# Generated by Django 2.2 on 2023-11-24 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_chatbot_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='max_tokens',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='temperature',
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=1,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['max_tokens'], name='chatbot_max_tokens'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['temperature'], name='chatbot_temperature'),
        ),
    ]
