# Generated by Django 2.2 on 2023-11-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_max_tokens_temperature_in_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='campaignactivity',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
        migrations.DeleteModel(
            name='CampaignActivity',
        ),
    ]
