# Generated by Django 2.2 on 2023-11-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_remove_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chatbot',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='conversations',
                to='contact.Chatbot',
            ),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='conversations',
                to='contact.Contact',
            ),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='chatbot',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='corpora',
                to='contact.Chatbot',
            ),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='conversation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='questions',
                to='contact.Conversation',
            ),
        ),
    ]
