# Generated by Django 2.2 on 2023-12-01 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='temperature',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
