# Generated by Django 2.2 on 2023-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_temperature_decimal_field_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt3', 'chatgpt3'),
                    ('echo', 'echo'),
                    ('llama2-7b', 'llama2-7b'),
                    ('llama2-13b', 'llama2-13b'),
                ],
                default='echo',
                max_length=10,
            ),
        ),
    ]
