# Generated by Django 2.2 on 2023-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_chatbot_llm_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_prompt',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='prompt',
            new_name='system_prompt',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='reference_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='user_prompt',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['system_prompt'], name='chatbot_system_prompt'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['user_prompt'], name='chatbot_user_prompt'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['reference_limit'], name='chatbot_reference_limit'),
        ),
    ]
