# Generated by Django 2.2 on 2023-12-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_chatbot_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='system_prompt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user_prompt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
