# Generated by Django 2.2 on 2023-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_chatbot_prompt_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='echo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[('chatgpt3', 'chatgpt3'), ('llama2-7b', 'llama2-7b'), ('llama2-13b', 'llama2-13b')],
                default='chatgpt3',
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['echo'], name='chatbot_echo'),
        ),
    ]
