# Generated by Django 2.2 on 2024-02-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_echo_as_boolean_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_nn_embedding',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_nn_llm',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_max_tokens',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_temperature',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_system_prompt',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_user_prompt',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_reference_limit',
        ),
        migrations.RemoveIndex(
            model_name='chatbot',
            name='chatbot_echo',
        ),
        migrations.RemoveIndex(
            model_name='qanda',
            name='q_and_a_answer',
        ),
        migrations.RemoveIndex(
            model_name='qanda',
            name='q_and_a_question',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created'], name='contact_created'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created'], name='group_created'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['created'], name='opportunity_created'),
        ),
    ]
