# Generated by Django 2.2 on 2024-02-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_removed_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='similarity',
            field=models.CharField(
                choices=[
                    ('cosine_similarity', 'cosine_similarity'),
                    ('dot_product', 'dot_product'),
                    ('euclidean_distance', 'euclidean_distance'),
                ],
                default='euclidean_distance', max_length=20),
        ),
    ]
