# Generated by Django 2.2 on 2024-03-27 09:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_vector_similarity_formula_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('content', models.TextField()),
                ('distance', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hyperlink', models.URLField()),
            ],
            options={
                'db_table': 'chunk',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'question_set',
            },
        ),
        migrations.CreateModel(
            name='QuestionSetTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('language_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'question_set_translation',
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ground_truth', models.TextField()),
                ('language_id', models.IntegerField()),
                ('question', models.TextField()),
            ],
            options={
                'db_table': 'question_translation',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('generated_answer', models.TextField(null=True)),
                ('metric', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('language_id', models.IntegerField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(
                    choices=[
                        ('retrieval_test', 'retrieval_test'),
                        ('answer_comparison_test', 'answer_comparison_test'),
                    ],
                    default='retrieval_test',
                    max_length=20,
                )),
                ('metric', models.CharField(
                    choices=[
                        ('ranking', 'ranking'),
                        ('exact_match', 'exact_match'),
                        ('rougel', 'rougel'),
                    ],
                    max_length=20,
                )),
                ('rag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'test_type',
            },
        ),
        migrations.AddIndex(
            model_name='testtype',
            index=models.Index(fields=['created'], name='test_type_created'),
        ),
        migrations.AddIndex(
            model_name='testtype',
            index=models.Index(fields=['name'], name='test_type_name'),
        ),
        migrations.AddIndex(
            model_name='testtype',
            index=models.Index(fields=['metric'], name='test_type_metric'),
        ),
        migrations.AddField(
            model_name='test',
            name='chatbot_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chatbot_tests',
                to='contact.Chatbot',
            ),
        ),
        migrations.AddField(
            model_name='test',
            name='question_set_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='set_tests',
                to='contact.QuestionSet',
            ),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='type_tests',
                to='contact.TestType',
            ),
        ),
        migrations.AddField(
            model_name='result',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Question'),
        ),
        migrations.AddField(
            model_name='result',
            name='test_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='results',
                to='contact.Test',
            ),
        ),
        migrations.AddField(
            model_name='questiontranslation',
            name='question_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='question_translations',
                to='contact.Question',
            ),
        ),
        migrations.AddField(
            model_name='questionsettranslation',
            name='question_set_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='set_translations',
                to='contact.QuestionSet',
            ),
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['id'], name='question_set_id'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_set_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='contact.QuestionSet',
            ),
        ),
        migrations.AddField(
            model_name='chunk',
            name='result_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chunks',
                to='contact.Result',
            ),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['created'], name='test_created'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['id'], name='test_id'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['created'], name='result_created'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['id'], name='result_id'),
        ),
        migrations.AddIndex(
            model_name='questiontranslation',
            index=models.Index(fields=['created'], name='question_translation_created'),
        ),
        migrations.AddIndex(
            model_name='questiontranslation',
            index=models.Index(fields=['id'], name='question_translation_id'),
        ),
        migrations.AddIndex(
            model_name='questionsettranslation',
            index=models.Index(fields=['created'], name='set_translation_created'),
        ),
        migrations.AddIndex(
            model_name='questionsettranslation',
            index=models.Index(fields=['id'], name='question_set_translation_id'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['id'], name='question_id'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['created'], name='chunk_created'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['id'], name='chunk_id'),
        ),
    ]
