# Generated by Django 2.2 on 2024-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_test_question_set_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsettranslation',
            name='question_set_id',
        ),
        migrations.AddField(
            model_name='questionset',
            name='member_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionset',
            name='name',
            field=models.CharField(default='empty set', max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['name'], name='question_set_name'),
        ),
        migrations.DeleteModel(
            name='QuestionSetTranslation',
        ),
    ]
