# Generated by Django 2.2 on 2024-04-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_question_set_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_set_id',
            new_name='question_set',
        ),
    ]
