# Generated by Django 2.2 on 2024-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0023_question_set_id_to_question_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontranslation',
            old_name='ground_truth',
            new_name='chunk',
        ),
        migrations.AddField(
            model_name='questiontranslation',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
