# Generated by Django 2.2 on 2024-05-28 12:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_remove_test_chunk_testtype_result_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('classes', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('name', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'exclusion',
            },
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['created'], name='exclusion_created'),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['id'], name='exclusion_id'),
        ),
        migrations.AddIndex(
            model_name='exclusion',
            index=models.Index(fields=['name'], name='exclusion_name'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='exclusion',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='exclusions',
                to='contact.Exclusion',
            ),
        ),
    ]
