# Generated by Django 2.2 on 2024-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_exclusion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt3', 'chatgpt3'),
                    ('chatgpt4', 'chatgpt4'),
                    ('llama2-7b', 'llama2-7b'),
                    ('llama2-13b', 'llama2-13b'),
                ],
                default='chatgpt3',
                max_length=10,
            ),
        ),
    ]
