# Generated by Django 2.2 on 2024-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0027_chatgpt4_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='encoder',
            field=models.CharField(
                choices=[('dragon_plus', 'dragon_plus'), ('use4', 'use4'), ('test_encoder', 'test_encoder')],
                default='use4',
                max_length=12,
            ),
        ),
    ]
