# Generated by Django 2.2 on 2024-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_encoders_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chunk_overlap',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chunk_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
    ]
