# Generated by Django 2.2 on 2024-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_threshold_chunk_size_and_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='bm25_limit',
            field=models.IntegerField(default=1),
        ),
    ]
