# Generated by Django 2.2 on 2024-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_bm25_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='encoder',
            field=models.CharField(
                choices=[
                    ('cix_encoder', 'cix_encoder'),
                    ('dragon_plus', 'dragon_plus'),
                    ('use4', 'use4'),
                    ('test_encoder', 'test_encoder'),
                ],
                default='use4',
                max_length=12,
            ),
        ),
    ]
