# Generated by Django 2.2 on 2024-10-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_cix_encoder_as_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='bm25_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt4', 'chatgpt4'),
                    ('llama2-7b', 'llama2-7b'),
                    ('llama2-13b', 'llama2-13b'),
                ],
                default='chatgpt4',
                max_length=10,
            ),
        ),
    ]
