# Generated by Django 2.2 on 2024-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_bm25_limit_default_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='cookie_consent_text',
            field=models.CharField(
                default=(
                    'This Chatbot uses only essential cookies. '
                    'You must accept the essential cookies to use this Chatbot.',
                ),
                max_length=255,
            ),
        ),
    ]
