# Generated by Django 2.2 on 2024-11-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_chatbot_add_cookie_consent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='pdf_scraping',
            field=models.CharField(
                choices=[('pdf', 'pdf'), ('pdf_hi_res', 'pdf_hi_res')],
                default='pdf',
                max_length=16,
            ),
        ),
    ]
