# Generated by Django 2.2 on 2024-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_pdf_scraping_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt4', 'chatgpt4'),
                    ('uccix_instruct', 'uccix_instruct'),
                ],
                default='chatgpt4',
                max_length=15,
            ),
        ),
    ]
