# Generated by Django 2.2 on 2024-11-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0035_uccix_instruct_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='layout',
            field=models.CharField(
                choices=[('window', 'window'), ('widget', 'widget')],
                default='window', max_length=6),
        ),
    ]
