# Generated by Django 2.2 on 2024-11-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_chatbot_add_layout_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_header_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_header_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='cookie_consent_text',
            field=models.CharField(
                default=(
                    'This Chatbot uses only essential cookies. '
                    'You must accept the essential cookies to use this Chatbot.',
                ),
                max_length=255,
            ),
        ),
    ]
