# Generated by Django 2.2 on 2024-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0037_chatbot_add_header_title_and_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='button_position_from_right',
            new_name='horizontal_percentage',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='button_position_from_bottom',
            new_name='vertical_percentage',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='horizontal_position',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='right', max_length=6),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='vertical_position',
            field=models.CharField(choices=[('top', 'top'), ('bottom', 'bottom')], default='bottom', max_length=6),
        ),
    ]
