# Generated by Django 2.2 on 2024-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0038_chatbot_update_position_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='content_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['content_type'], name='corpus_content_type'),
        ),
    ]
