# Generated by Django 2.2 on 2024-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0039_content_type_status_code_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='hyperlink',
            field=models.URLField(max_length=255),
        ),
    ]
