# Generated by Django 2.2 on 2025-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0040_url_max_length_255'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='hyperlink',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
