# Generated by Django 2.2 on 2025-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0041_filename_in_corpus_and_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='contact_information',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='intent_prompt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='smalltalk_prompt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='qanda',
            name='intent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='system_prompt',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user_prompt',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
