# Generated by Django 2.2 on 2025-01-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0042_agentic_ai_properties_chatbot_qanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='cookie_consent_text',
            field=models.CharField(
                default=(
                    'This Chatbot uses only essential cookies. '
                    'You must accept the essential cookies to use this Chatbot.',
                ),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt4', 'chatgpt4'),
                    ('deepseek', 'deepseek'),
                    ('uccix_instruct', 'uccix_instruct'),
                ],
                default='chatgpt4',
                max_length=15,
            ),
        ),
    ]
