# Generated by Django 2.2 on 2025-01-29 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0043_deepseek'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cookie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='conversations',
                to='contact.Contact',
            ),
        ),
    ]
