# Generated by Django 2.2 on 2025-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0045_uccix_instruct_70b'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='apply_intent_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='apply_reranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='reranker',
            field=models.CharField(
                choices=[
                    ('chatgpt4', 'chatgpt4'),
                    ('deepseek', 'deepseek'),
                    ('uccix_instruct', 'uccix_instruct'),
                    ('uccix_instruct_70b', 'uccix_instruct_70b'),
                    ('minilm-l-6-v2', 'minilm-l-6-v2'),
                ],
                default='minilm-l-6-v2',
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='reranking_limit',
            field=models.IntegerField(default=5),
        ),
    ]
