# Generated by Django 2.2 on 2025-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0046_reranking_for_chunks_in_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='intent_prompt',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='smalltalk_prompt',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='system_prompt',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user_prompt',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
