# Generated by Django 5.0.13 on 2025-04-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0048_django5'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='api_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='corpus_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt4.1', 'chatgpt4.1'),
                    ('chatgpt4', 'chatgpt4'),
                    ('deepseek', 'deepseek'),
                    ('uccix_instruct', 'uccix_instruct'),
                    ('uccix_instruct_70b', 'uccix_instruct_70b'),
                ],
                default='deepseek',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='reranker',
            field=models.CharField(
                choices=[
                    ('chatgpt4.1', 'chatgpt4.1'),
                    ('chatgpt4', 'chatgpt4'),
                    ('deepseek', 'deepseek'),
                    ('uccix_instruct', 'uccix_instruct'),
                    ('uccix_instruct_70b', 'uccix_instruct_70b'),
                    ('minilm-l-6-v2', 'minilm-l-6-v2'),
                ],
                default='minilm-l-6-v2',
                max_length=128,
            ),
        ),
    ]
