# Generated by Django 5.0.13 on 2025-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0049_api_key_corpus_names_chatgpt4_1_in_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='question_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
