# Generated by Django 5.0.13 on 2025-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0050_q_and_a_add_question_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('chatgpt4.1', 'chatgpt4.1'),
                    ('chatgpt4', 'chatgpt4'),
                    ('UCCIX-Mistral-24B', 'UCCIX-Mistral-24B'),
                    ('uccix_instruct', 'uccix_instruct'),
                    ('uccix_instruct_70b', 'uccix_instruct_70b'),
                ],
                default='UCCIX-Mistral-24B',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='reranker',
            field=models.CharField(
                choices=[
                    ('chatgpt4.1', 'chatgpt4.1'),
                    ('chatgpt4', 'chatgpt4'),
                    ('UCCIX-Mistral-24B', 'UCCIX-Mistral-24B'),
                    ('uccix_instruct', 'uccix_instruct'),
                    ('uccix_instruct_70b', 'uccix_instruct_70b'),
                    ('minilm-l-6-v2', 'minilm-l-6-v2'),
                ],
                default='minilm-l-6-v2',
                max_length=128,
            ),
        ),
    ]
