# Generated by Django 5.0.13 on 2025-11-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0051_deprecate_deepseek'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='no_reference_answer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
