# Generated by Django 5.0.13 on 2025-11-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0052_chatbot_no_reference_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='apply_safety_classifier',
            field=models.BooleanField(default=False),
        ),
    ]
