# Generated by Django 5.0.13 on 2026-01-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0053_chatbot_apply_safety_classifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated']},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated'], name='conversation_updated'),
        ),
    ]
