# Generated by Django 5.0.13 on 2026-01-13 12:59

from django.db import migrations
from django.db.models import F


def set_last_message_at(apps, schema_editor):
    conversation = apps.get_model('contact', 'Conversation')
    conversation.objects.filter(last_message_at__isnull=True).update(last_message_at=F('created'))


def reverse_last_message_at(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0055_conversation_last_message_at'),
    ]

    operations = [
        migrations.RunPython(set_last_message_at, reverse_last_message_at),
    ]
