# Generated by Django 5.0.13 on 2026-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0057_add_mistral_large_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='encoder',
            field=models.CharField(
                choices=[
                    ('cix_encoder', 'cix_encoder'),
                    ('test_encoder', 'test_encoder'),
                ],
                default='cix_encoder',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='nn_llm',
            field=models.CharField(
                choices=[
                    ('UCCIX-Mistral-24B', 'UCCIX-Mistral-24B'),
                    ('Mistral-Large-3', 'Mistral-Large-3'),
                ],
                default='UCCIX-Mistral-24B',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='reranker',
            field=models.CharField(
                choices=[
                    ('UCCIX-Mistral-24B', 'UCCIX-Mistral-24B'),
                    ('Mistral-Large-3', 'Mistral-Large-3'),
                    ('minilm-l-6-v2', 'minilm-l-6-v2'),
                ],
                default='minilm-l-6-v2',
                max_length=20,
            ),
        ),
    ]
